use core::marker::PhantomData;
use failure::Error;
use io_watch::poll::Poller;
use regex::{Captures, Regex};

/// Manages events generated by a Poller that outputs strings
/// This takes events in the form of regex patterns + closure callbacks
/// Incoming strings can be processed by filters beforehand
pub struct EventManager<T: Poller<Output = String>, F: Default + Clone> {
    poll: T,
    registered_events: Vec<Event<F>>,
    filters: Vec<Box<Fn(String, &mut F) -> String>>,
    phanthom_f: PhantomData<F>,
}

impl<T: Poller<Output = String>, F: Default + Clone> EventManager<T, F> {
    /// Creates a new EventManager given a Poller of Strings
    pub fn new(poll: T) -> Self {
        Self {
            poll,
            registered_events: Vec::new(),
            filters: Vec::new(),
            phanthom_f: Default::default(),
        }
    }

    /// Register a new event that can be called back when a matching string is found
    pub fn register_event(
        &mut self,
        pattern: &str,
        callback: impl Fn(Captures, F) + 'static,
    ) -> Result<(), Error> {
        self.registered_events.push(Event::new(pattern, callback)?);
        Ok(())
    }

    /// Register a filter to preprocess strings before finding the matching events
    pub fn register_filter(&mut self, filter: impl Fn(String, &mut F) -> String + 'static) {
        self.filters.push(Box::new(filter));
    }

    //TODO: Find a good way to cancel this infinite loop

    /// Run event manager.
    /// This will only return on Error
    pub fn run(&mut self) -> Result<!, Error> {
        loop {
            let strings_to_process = self.poll.wait_and_read()?;

            strings_to_process
                .into_iter()
                .map(|mut string| {
                    let mut info = F::default();
                    for filter in &self.filters {
                        string = (*filter)(string, &mut info);
                    }
                    (string, info)
                })
                .for_each(|data| {
                    let (string, info) = data;

                    let mut found = false;

                    for event in &self.registered_events {
                        if let Some(captures) = event.regex.captures(&string) {
                            let callback = &*event.callback;

                            callback(captures, info.clone());

                            found = true;
                        };
                    }

                    if !found {
                        //println!("{:?}", string);
                    }
                });
        }
    }
}

struct Event<T> {
    regex: Regex,
    callback: Box<Fn(Captures, T)>,
}

impl<T> Event<T> {
    pub fn new(pattern: &str, callback: impl Fn(Captures, T) + 'static) -> Result<Self, Error> {
        Ok(Self {
            regex: Regex::new(pattern)?,
            callback: Box::new(callback),
        })
    }
}
